[workspace]
members = [
    "crates/xen",
    "crates/xen-bindings",
    "crates/xen-ioctls",
    "crates/xen-store",
    "crates/xen-sys",
]
exclude = [
    "examples/oxerun",
    "examples/ioctls",
    "examples/xstore",
]

