[workspace]
resolver = "2"
members = [
    "crates/xen",
    "crates/xen-bindings",
    "crates/xen-ioctls",
    "crates/xen-store",
    "crates/xen-sys",
]
exclude = [
    "crates/oxerun",
    "examples/ioctls",
    "examples/xstore",
]
