#include <xen-compat.h>
#include <xen/types.h>
#include <arch-x86/xen.h>
#include <arch-x86/xen-x86_64.h>
#include <domctl.h>
#include <hvm/ioreq.h>
#include <io/xenbus.h>
#include <xenctrl.h>
#include <xendevicemodel.h>
#include <xengnttab.h>
#include <xenstore.h>
